"use strict";
var index_1 = require('./index');
exports.COMPONENT_DECLARATIONS = [
    index_1.GuestHomeComponent,
    index_1.FooterComponent,
    index_1.HeaderComponent,
    index_1.AboutusComponent,
    index_1.UserLoginComponent,
    index_1.PageTitleComponent,
    index_1.UserDashboardComponent,
    index_1.UserSignupComponent,
    index_1.TokenComponent,
    index_1.MidHeaderComponent,
    index_1.UserProfileComponent,
    index_1.EditUserProfileComponent,
    index_1.AdminDashboardComponent,
    index_1.AdminHeaderComponent,
    index_1.VendorSignupComponent,
    index_1.VendorDashboardComponent,
    index_1.VendorHeaderComponent,
    index_1.ListVendorComponent,
    index_1.AdminPackageListComponent,
    index_1.AdminAddPackageComponent,
    index_1.AdminEditPackageComponent,
    index_1.UserPackageSearchComponent,
    index_1.UserPackageListComponent,
    index_1.UserOrderListComponent,
    index_1.AdminListServiceComponent,
    index_1.AdminAddServiceComponent,
    index_1.AdminEditServiceComponent,
    index_1.AdminOrderListComponent,
    index_1.VendorOrderListComponent,
    index_1.VendorPackageListComponent
];
//# sourceMappingURL=componentlist.js.map