import { 
	GuestHomeComponent,
	FooterComponent,
	HeaderComponent,
	AboutusComponent,
	UserLoginComponent,
	PageTitleComponent,
	UserDashboardComponent,
	UserSignupComponent,
	TokenComponent,
	MidHeaderComponent ,
	UserProfileComponent,
	EditUserProfileComponent,
	AdminDashboardComponent,
	AdminHeaderComponent,
	VendorSignupComponent,
	VendorDashboardComponent,
	VendorHeaderComponent,
	ListVendorComponent,
	AdminPackageListComponent,
	AdminAddPackageComponent,
	AdminEditPackageComponent
} from './index';

export const COMPONENT_DECLARATIONS = [
  GuestHomeComponent,
  FooterComponent,
  HeaderComponent,
  AboutusComponent,
  UserLoginComponent,
  PageTitleComponent,
  UserDashboardComponent,
  UserSignupComponent,
  TokenComponent,
  MidHeaderComponent,
  UserProfileComponent,
  EditUserProfileComponent,
  AdminDashboardComponent,
  AdminHeaderComponent,
  VendorSignupComponent,
  VendorDashboardComponent,
  VendorHeaderComponent,
  ListVendorComponent,
  AdminPackageListComponent,
  AdminAddPackageComponent,
  AdminEditPackageComponent
];

